parameters:
#    git_gui.example.class: Git\Bundle\GuiBundle\Example

services:
#    git_gui.example:
#        class: %git_gui.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
